#!/bin/bash

echo "notes-to-self" > README.md
echo -e '=============\n' >> README.md

cat notes-to-self.wiki/Home.md >> README.md
cat notes-to-self.wiki/markdown-syntax.md >> README.md
cat notes-to-self.wiki/dime-a-dozen-ideas-for-interesting-weekend-projects.md >> README.md
cat notes-to-self.wiki/practical-find.md >> README.md
cat notes-to-self.wiki/practical-grep.md >> README.md
cat notes-to-self.wiki/don\'t-ask,-don\'t-tell.md >> README.md

echo "Done!"
